### PR TITLE
Allow running flavour scripts on non-persistent pots

### LINKED ISSUE #238: [BUG] Flavour scripts don't work on non-persistent pots
**Describe the bug**
When setting the persistent flag to _OFF_ in a flavour (`set-attribute -A persistent -V OFF`), running the flavour script fails.

**To Reproduce**
Create a flavour that contains a file _<flavour>_ that contains `set-attribute -A persistent -V OFF` and has a trivial flavour script `flavour.sh`. Try to create a pot and see it fail.

**Expected behavior**
Creating the pot should work.

**Additional context**
This used to work, probably by accident, since we had various sleeps inside pots that would keep it alive long enough to launch a command.

Since we no longer have background sleeps to keep the pot alive, it shuts down. The work to properly lock start/stop might also contribute to this.

A clean solution could be to override flv_set_cmd temporarily and run the non-persistent pot once - alternatively, start could grow a special parameter we can use for this case.

The workaround is to not create non-persistent pots (in case they are non-persistent for use in nomad, `pot prepare` overrides the persistent flag anyway).

### PR DESCRIPTION
**Pull request by grembo**
Fixes #238

### CODE REVIEW

**Comment by grembo** [comment]
@bretton This patch should fix your problem, could you please give it a shot?

**Comment by bretton** [comment]
> @bretton This patch should fix your problem, could you please give it a shot?

no luck, it doesn't start the first jail either, just goes straight to the error. 
```
###>  pot name-amd64-13_1 is not in a state where it can start
fbsd-update.sh -> /mnt/srv/pot/jails/name-amd64-13_1/m/tmp/fbsd-update.sh
=====>  Executing fbsd-update script on name-amd64-13_1
jexec: jail "name-amd64-13_1" not found
###>  create: flavour fbsd-update failed (script)
```
and without -f fbsd-update
```
###>  pot name-amd64-13_1 is not in a state where it can start
name.sh -> /mnt/srv/pot/jails/name-amd64-13_1/m/tmp/name.sh
=====>  Executing name script on name-amd64-13_1
jexec: jail "name-amd64-13_1" not found
###>  create: flavour name failed (script)
```

**Comment by grembo** [comment]
That sounds like you have some leftover files from a previous failed start. Check jls if anything is running and then remove /tmp/pot_status* files.

**Comment by bretton** [comment]
> remove /tmp/pot_status* files.

aha, this did the trick and patch worked this time

**Comment by grembo** [comment]
@bretton Luca fixed a bug in #235 where destroy left status files behind (which is what you might be experiencing here and unrelated to the problem). So please make sure to destroy the test pot and remove its status file from /tmp (or patch your pot installation) before trying.

**Comment by grembo** [comment]
This is the patch in question:

https://github.com/bsdpot/pot/commit/c11c744aae15f289b1e8bb9b7add554e575045d6.diff#diff-f2bfc9bdc864b91bd44c3884e3e777844f866e1c78898d7f1db4c7ad2bf98100

I think it's time to tag a new release soon.

**Comment by grembo** [comment]
As this was tested successfully (locally + one user), I'll merge it

**Pull request merged**
